export const VOICE_LANGUAGES = [
  ['zh', 'Chinese'],
  ['en', 'English'],
  ['ja', 'Japanese'],
  ['ko', 'Korean'],
  ['es', 'Spanish'],
  ['fr', 'French'],
  ['de', 'German'],
  ['it', 'Italian'],
  ['pt', 'Portuguese'],
  ['ru', 'Russian'],
  ['ar', 'Arabic'],
  ['hi', 'Hindi'],
  ['id', 'Indonesian'],
  ['ms', 'Malay'],
  ['th', 'Thai'],
  ['vi', 'Vietnamese'],
  ['tr', 'Turkish'],
  ['pl', 'Polish'],
  ['nl', 'Dutch'],
  ['sv', 'Swedish'],
  ['no', 'Norwegian'],
  ['da', 'Danish'],
  ['fi', 'Finnish'],
  ['el', 'Greek'],
  ['he', 'Hebrew'],
  ['km', 'Khmer'],
  ['lo', 'Lao'],
  ['my', 'Burmese'],
  ['sw', 'Swahili'],
  ['tl', 'Tagalog'],
]

export const CHINESE_DIALECTS = [
  ['mandarin', 'Mandarin'],
  ['sichuanese', 'Sichuanese'],
  ['cantonese', 'Cantonese'],
  ['wu', 'Wu'],
  ['northeastern', 'Northeastern Mandarin'],
  ['henan', 'Henan dialect'],
  ['shaanxi', 'Shaanxi dialect'],
  ['shandong', 'Shandong dialect'],
  ['tianjin', 'Tianjin dialect'],
  ['minnan', 'Hokkien / Minnan'],
]

export const VOICE_MODES = [
  ['trained_profile', 'Use a saved voice'],
  ['basic_tts', 'Generate a standard voice'],
  ['voice_design', 'Describe the voice I want'],
  ['controllable_clone', 'Clone from a reference clip'],
  ['ultimate_clone', 'Best-quality clone'],
  ['lora_finetune', 'Use a custom trained voice'],
]

export const VOICE_STYLE_PRESETS = [
  ['professional_calm', 'Professional and calm'],
  ['friendly_natural', 'Friendly and natural'],
  ['clear_slow', 'Clear and slightly slow'],
  ['energetic', 'Energetic'],
  ['warm_storytelling', 'Warm storytelling'],
  ['serious_authoritative', 'Serious and authoritative'],
]
